export const MENTAL_HEALTH_GLOSSARY: Record<string, { rw: string; en: string; category: string }> = {
  "mental health": { en: "Mental health", rw: "Ubuzima bwo mu mutwe", category: "Condition" },
  "anxiety": { en: "Anxiety", rw: "Impungenge", category: "Condition" },
  "depression": { en: "Depression", rw: "Agahinda gakabije", category: "Condition" },
  "stress": { en: "Stress", rw: "Umunaniro ukabije", category: "Condition" },
  "trauma": { en: "Trauma", rw: "Ihungabana", category: "Condition" },
  "crisis": { en: "Crisis", rw: "Ikibazo gikabije", category: "Condition" },
  "burnout": { en: "Burnout", rw: "Kunanirwa bikabije", category: "Condition" },
  "panic attack": { en: "Panic attack", rw: "Gutinya bikabije", category: "Condition" },
  "self-harm": { en: "Self-harm", rw: "Kwigirira nabi", category: "Condition" },
  "suicide": { en: "Suicide", rw: "Kwiyahura", category: "Condition" },
  "wellness": { en: "Wellness", rw: "Kumera neza", category: "Condition" },
  "mind": { en: "Mind", rw: "Ubwenge", category: "Condition" },
  "grief": { en: "Grief", rw: "ISHAVU", category: "Emotion" },
  "fear": { en: "Fear", rw: "Ubwoba", category: "Emotion" },
  "sadness": { en: "Sadness", rw: "Agahinda", category: "Emotion" },
  "anger": { en: "Anger", rw: "Uburakari", category: "Emotion" },
  "loneliness": { en: "Loneliness", rw: "Kwiyumva wenyine", category: "Emotion" },
  "hope": { en: "Hope", rw: "Ibyiringiro", category: "Emotion" },
  "joy": { en: "Joy", rw: "Ibyishimo", category: "Emotion" },
  "shame": { en: "Shame", rw: "Isoni", category: "Emotion" },
  "guilt": { en: "Guilt", rw: "Ibyaha", category: "Emotion" },
  "worry": { en: "Worry", rw: "Gutinya", category: "Emotion" },
  "mood": { en: "Mood", rw: "Imyitwarire y'umutima", category: "Emotion" },
  "feelings": { en: "Feelings", rw: "Ibyiyumvo", category: "Emotion" },
  "emotions": { en: "Emotions", rw: "Amarangamutima", category: "Emotion" },
  "therapy": { en: "Therapy", rw: "Ubuvuzi bwo guturisha umutima", category: "Support" },
  "counselling": { en: "Counselling", rw: "Ubujyanama", category: "Support" },
  "support": { en: "Support", rw: "ubufasha", category: "Support" },
  "healing": { en: "Healing", rw: "Gukira", category: "Support" },
  "recovery": { en: "Recovery", rw: "Gusubirana", category: "Support" },
  "breathe": { en: "Breathe", rw: "Humeka", category: "Action" },
  "relax": { en: "Relax", rw: "Tegereza", category: "Action" },
  "journal": { en: "Journal", rw: "Andika iby’uyumunsi", category: "Action" },
  "meditate": { en: "Meditate", rw: "itekerezeho", category: "Action" },
  "rest": { en: "Rest", rw: "Ruhuka", category: "Action" },
  "talk to someone": { en: "Talk to someone", rw: "Bwira umuntu", category: "Action" },
  "seek mental health support": { en: "Seek mental health support", rw: "Shaka ubufasha mu buzima bwo mu mutwe", category: "Action" },
  "exercise": { en: "Exercise", rw: "Imyitozo ngororamubiri", category: "Action" },
  "sleep": { en: "Sleep", rw: "Sinzira", category: "Action" },
  "eat well": { en: "Eat well", rw: "Rya neza", category: "Action" },
  "how are you feeling?": { en: "How are you feeling?", rw: "Umeze ute?", category: "App UI" },
  "you are not alone": { en: "MIND SUPPORTED, LIFE EMPOWERED", rw: "GUSHYIGIKIRA IMITEKEREREZE, GUKOMEZA UBUZIMA", category: "App UI" },
  "we are here for you": { en: "We are here for you", rw: "Turi hano ngo tugufashe", category: "App UI" },
  "take a deep breath": { en: "Take a deep breath", rw: "Humeka neza", category: "App UI" },
  "log your mood": { en: "Log your mood", rw: "Andika uko wiyumva", category: "App UI" },
  "daily check-in": { en: "Daily check-in", rw: "Kwisuzuma buri munsi", category: "App UI" },
  "emergency help": { en: "Emergency help", rw: "Ubufasha bw'ihutirwa", category: "App UI" },
  "settings": { en: "Settings", rw: "Igenamiterere", category: "App UI" },
  "notifications": { en: "Notifications", rw: "Amamenyesha", category: "App UI" },
  "get started": { en: "Get started", rw: "Tangira", category: "App UI" }
};
